# Generated by Django 2.2.16 on 2022-01-26 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(help_text='Enter the Name of category', max_length=200, unique=True, verbose_name='Name of categories'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(help_text='Enter the Name of genre', max_length=200, unique=True, verbose_name='Name of genre'),
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(help_text='Category of the Title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='categories.Categories', verbose_name='Category of the Title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, help_text='Small description of the Title', null=True, verbose_name='Title description'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(help_text='Genre of the Title', through='categories.TitlesGenres', to='categories.Genres', verbose_name='Genre of the Title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Enter the Name of title', max_length=200, verbose_name='Name of titles'),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Rating from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating of the Title'),
        ),
        migrations.AlterField(
            model_name='titlesgenres',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titlesgenres', to='categories.Genres'),
        ),
        migrations.AlterField(
            model_name='titlesgenres',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titlesgenres', to='categories.Title'),
        ),
    ]
