# Generated by Django 2.2.16 on 2022-01-27 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20220127_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(help_text='Name of categories', max_length=200, unique=True, verbose_name='Name of categories'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(help_text='Name of genre', max_length=200, unique=True, verbose_name='Name of genre'),
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(help_text='Name of categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='categories.Categories', verbose_name='Name of categories'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, help_text='Text of descriptions', null=True, verbose_name='Text of descriptions'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(help_text='Name of ganres', through='categories.TitlesGenres', to='categories.Genres', verbose_name='Name of ganres'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Name of titles', max_length=200, verbose_name='Name of titles'),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Score of ratings', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Score of ratings'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Release year of titles', verbose_name='Release year of titles'),
        ),
    ]
